### PR TITLE
Random suffix generation in postgres module

### PR DESCRIPTION
**Pull request by sindrel**
* support for random suffix generation if toggled
* supports a static suffix, a randomly generated suffix, or both
* features: enable/disable random suffix, set random suffix length
* randomly generated suffix is hex string, i.e. "foo-dev-fa4e"
* default is 4 char hex string only: "my-great-app-dev-3d2a"
* updated readme

### CODE REVIEW

**Comment by sindrel** [comment]
Perhaps default static suffix should still be "postgres" (might be excessive?):

The default would then be: "my-great-app-dev-postgres-3d2a"

**Comment by AlexanderBrevig** [comment]
I see what you're doing now. You are adding a random suffix to the suffix - if it is enabled.
Ok this makes sense.

I think setting the default to false makes for a clearer API. This way the module has to explicitly say true and it will make sense when you see the output.

**Comment by sindrel** [comment]
> I would love it if we could check the length of the provided suffix parameter, only if length is zero do we use a random one?

I tried by simply setting the random_id byte length in main.tf to 0, but it caused the tf provider to panic. There might be a better way around this.

> This is also a breaking change, in that we must change incoming suffixes with a - prefix.
> 
> Thoughts on this?

Good point. I'll commit a change re-introducing the - prefix when only a static suffix is set.

**Comment by Spikra** [comment]
In my opinion we should have three options for naming the database (if we are keeping backwards compatibility):
1. Default keep the same naming scheme as today
2. Set the whole name of the database
3. Optionally add fixed-length random suffix

If we are breaking backwards compatibility:
1. Default add fixed-length random suffix
2. Set the whole name of the database
3. Optional: keep current naming scheme

**Comment by sindrel** [comment]
> In my opinion we should have three options for naming the database (if we are keeping backwards compatibility):
> 
>     1. Default keep the same naming scheme as today
> 
>     2. Set the whole name of the database
> 
>     3. Optionally add fixed-length random suffix

By same naming scheme as today, are you referring to current running dbs w/o suffix?

See [latest commit](https://github.com/entur/terraform/pull/13/commits/10b415bf135778f71513699cdda663d48520e031).

Current module default is now:
"foo-dev-postgres-3d2a"

Optionally, any name override can be set using the db_instance_custom_name variable, i.e.:
"i-am-a-teapot-asdf"

**Comment by sindrel** [comment]
Changes in [1a42251](https://github.com/entur/terraform/pull/13/commits/1a422517724c9f587e8c0c244d90105f0c202aae):

* default convention is: app-namespace-rand
* can be overridden with variable db_instance_custom_name
* other options removed

**Plan output:**

**Default:**
 module.postgres.module.sql-db_postgresql.google_sql_database_instance.default will be created
  + resource "google_sql_database_instance" "default" {
      + connection_name               = (known after apply)
      + database_version              = "POSTGRES_11"
      + first_ip_address              = (known after apply)
      + id                            = (known after apply)
      + ip_address                    = (known after apply)
      + master_instance_name          = (known after apply)
      + name                          = (known after apply)

[...]

module.postgres.module.sql-db_postgresql.google_sql_database_instance.default: Creation complete after 3m44s [id=redacted-env-3128]

**Override set to "foo":**
db_instance_custom_name = "foo" 
 module.postgres.module.sql-db_postgresql.google_sql_database_instance.default will be created
  + resource "google_sql_database_instance" "default" {
      + connection_name               = (known after apply)
      + database_version              = "POSTGRES_11"
      + first_ip_address              = (known after apply)
      + id                            = (known after apply)
      + ip_address                    = (known after apply)
      + master_instance_name          = (known after apply)
      + name                          = "foo"

**Pull request merged**
