### PR TITLE
Bucket module: Replace deprecated bucket_policy_only attribute with uniform_bucket_level_access

### PR DESCRIPTION
**Pull request by sindrel**
**Uniform bucket-level access** was known as **Bucket Policy Only** (`bucket_policy_only`) during Beta. This has now been changed, introducing changes in the API.
https://cloud.google.com/storage/docs/uniform-bucket-level-access

The use of `bucket_policy_only` will be removed in the next major release of the Google provider, in favor of the equivalent attribute `uniform_bucket_level_access`.
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/storage_bucket#bucket_policy_only

This PR replaces the use of `bucket_policy_only` with `uniform_bucket_level_access`.

```
Warning: Attribute is deprecated

  on .terraform/modules/bucket/modules/bucket/main.tf line 16, in resource "google_storage_bucket" "storage_bucket":
  16:   bucket_policy_only = var.bucket_policy_only

Please use the uniform_bucket_level_access as this field has been renamed by
Google.
```

### CODE REVIEW

**Comment by recet** [comment]
LGTM

**Review by recet — APPROVED** [review]
LGTM

**Review by AlexanderBrevig — APPROVED** [review]
LGTM

**Comment by AlexanderBrevig** [comment]
Will impact and slightly update https://github.com/entur/terraform/tree/bucket-refresh which I also hope we can accept a PR for.

**Pull request merged**
